version: '3.8'

services:
  copyright-free-media-reviewer:
    build: .
    container_name: copyright-free-media-reviewer
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./assets:/app/assets
    restart: always